@baseUrl = http://localhost:8092
@loansUrl = {{baseUrl}}/api/v1/loans

# GET health
GET {{baseUrl}}/actuator/health

###

# SHUTDOWN app via actuator
POST {{baseUrl}}/actuator/shutdown

###

# Refresh config using actuator
POST {{baseUrl}}/actuator/refresh

###

# GET build version
GET {{loansUrl}}/version

###

# GET java version
GET {{loansUrl}}/java-version

###

# GET env variable
GET {{loansUrl}}/env-variable/DB_USER

###

# GET contact information
GET {{loansUrl}}/contact-info

###
# Create a loan
POST {{loansUrl}}
Content-Type: application/json

{
  "mobileNumber": "+49171123456789"
}

###

# Fetch a loan
GET {{loansUrl}}/+49171123456789

###

# Update a loan
PUT {{loansUrl}}
Content-Type: application/json

{
  "mobileNumber": "+49171123456789",
  "loanNumber": "100207296912",
  "loanType": "Home Loan",
  "totalLoan": 76543,
  "amountPaid": 12345,
  "outstandingAmount": 64098
}