spring:
  config:
    activate:
      on-profile: "prod"


build:
    version: "0.8.0"

loans:
    message: "Learning how to create microservices - here: loans"
    contact:
        name: "Otto Ostermann, QA Lead"
        email: "otto@heinzi.de"
    support:
        - +49 171 11122223
        - +49 800 77778888