server:
    port: 8092

spring:
    application:
        name: loans
    profiles:
        active: prod
    datasource:
        url: jdbc:mysql://localhost:3307/loansdb
        username: root
        password: root
    #     url: jdbc:h2:mem:testdb
    #     driverClassName: org.h2.Driver
    #     username: sa
    #     password: ''
    # h2:
    #     console:
    #         enabled: true
    jpa:
        # database-platform: org.hibernate.dialect.H2Dialect
        # hibernate:
        #     ddl-auto: update
        show-sql: true
    sql:
        init:
            mode: always
    config:
        import: "optional:configserver:http://localhost:8071/"
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

management:
    endpoints:
        web:
            exposure:
                include: "*"

# --- MOVED TO CLOUD CONFIG SERVER
#     config:
#         import:
#             - "application_test.yml"
#             - "application_prod.yml"
#     profiles:
#         active:
#             # - "test"

# build:
#     version: "1.0.0"

# loans:
#     message: "Learning how to create microservices - here: cards"
#     contact:
#         name: "Hansi Hampelmann"
#         email: "hansi@heinzi.de"
#     support:
#         - +49 171 44455556
#         - +49 800 77778888    
